name: build and test

on: [push]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: docker://mmorse1217/patchwork:latest
    - name: Pull/build Docker image
      run: docker build --file Dockerfile --target=patchwork-build --cache-from="mmorse1217/patchwork:latest" --tag patchwork-build .
    - name: Build patchwork
      run: docker run --rm patchwork-build
