name: build and test

on: [push]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: docker://mmorse1217/patchwork:latest
    - name: Build patchwork
      run: docker run --rm -v${GITHUB_WORKSPACE}:/patchwork mmorse1217/patchwork:latest sh entrypoint.sh
