name: build and test

on: [push]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull/build Docker image
      run: docker build --file Dockerfile --target=patchwork-build --tag patchwork-build .
    - name: Build patchwork
      run: | 
        ls /patchwork
        ls /patchwork/cmake
        docker run --rm patchwork-build
